spring:
  application:
    name: shrek-codegen
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.11.132:3306/shrekdata?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&
    username: root
    password: 123456

mybatis:
   mapperLocations: classpath:/mapper/*.xml

server:
  port: 8188

management:
  endpoints:
    web:
      exposure:
        include: "*"

user:
  name: shrek